### ISSUE TITLE
Python Compress

### ISSUE THREAD

**Issue by ghost** [n3ws/fvduino#2]
python compress.py --lookback 7 --length 4 --name 3khall 3khall.h hallcompressed.h

this gives me a bigger file, how do I make it smaller?
what loopback and length setting did you use?

**Comment by n3ws** [comment]
Hi,

compress only works with bin files as input. It compresses the
bytes and makes either a header file or compressed bin file.

Please use --lookback 0 and --length 0 and compress will
search for the optimal values automatically:

python compress.py --lookback 0 --length 0 --name input.bin output.h

**Comment by n3ws** [comment]
Hi,

will add that if you want to assemble FV-1 programs to bin files (512 bytes
each), you can use the free FV1 assembler asfv1:
https://pypi.org/project/asfv1/
For example:

asfv1 -s 3khall.spn 3khall.bin

**Comment by n3ws** [comment]
Sorry,

the compress command shoud be:

python compress.py --lookback 0 --length 0 --name input input.bin output.h

**Comment by ghost** [comment]
Lees-iMac:Desktop lee$ asfv1 -s 3khall.spn 3khall.bin
Traceback (most recent call last):
  File "/usr/local/bin/asfv1", line 9, in <module>
    load_entry_point('asfv1==1.2.7', 'console_scripts', 'asfv1')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.13-intel/egg/asfv1.py", line 30, in <module>
ImportError: No module named builtins

**Comment by n3ws** [comment]
This is an issue with asfv1 installation.

Look at:
https://pypi.org/project/asfv1/#system-specific-installation

**Comment by ghost** [comment]
got it working

Lees-iMac:asfv1-1.2.7 lee$ asfv1 -s 3khall.spn 3khall.bin
FV-1 Assembler v1.2.7
info: Reading input from 3khall.spn
warning: SpinASM compatibility - literals 2,1 read as 2.0,1.0
info: Read 128 instructions from input
info: Writing binary output to 3khall.bin

**Comment by n3ws** [comment]
Per asfv1 installation instructions, you should try with python 3
on macOS. If that doesn't work, please contact asfv1 author for help.
